version: "3"

services:
    elastic-search:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
        restart: unless-stopped
        networks:
            - entomomachia
        environment:
            - discovery.type=single-node
        ports:
            - "9200:9200"
            - "9300:9300"
    kibana: 
        image: docker.elastic.co/kibana/kibana:7.7.0
        networks: 
            - entomomachia
        environment: 
            SERVER_NAME: kibana
            ELASTICSEARCH_HOSTS: http://elastic-search:9200
        ports:
            - "5601:5601"
    zookeeper:
        image: confluentinc/cp-zookeeper:latest
        restart: unless-stopped
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        ports:
            - 22181:2181
        networks:
            - entomomachia
    
    kafka:
        image: confluentinc/cp-kafka:latest
        restart: unless-stopped
        depends_on:
            - zookeeper
        ports:
            - 29092:29092
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        networks:
            - entomomachia

    general-classifier:
        build: mining/generalframework
        depends_on:
            - kafka
        networks: 
            - entomomachia
        environment:
            - DOCKER_RUNNING=true
            - MINING=classifier
        volumes:
            - ./mining/data:/opt/data/
            - ./logs:/opt/logs/
            - ./mining/generalframework:/opt/generalframework

    improve-labeller-model:
        build: mining/generalframework
        depends_on:
            - kafka
        networks: 
            - entomomachia
        environment:
            - DOCKER_RUNNING=true
            - MINING=improve_model
        volumes:
            - ./mining/data:/opt/data/
            - ./logs:/opt/logs/
            - ./mining/generalframework:/opt/generalframework

    elastic-facade-server:
        build: backend/elasticInterface/server
        depends_on:
            - elastic-search 
        networks: 
            - entomomachia
        environment:
            - DOCKER_RUNNING=true
        volumes:
            - ./logs:/opt/logs/
            - ./backend/elasticInterface/server:/opt/server
        ports:
            - 1099:1099
    elastic-facade-client:
        build: backend/elasticInterface/clienttest
        depends_on:
            - elastic-facade-server
        networks: 
            - entomomachia
        environment:
            - DOCKER_RUNNING=true
        volumes:
            - ./logs:/opt/logs/
            - ./backend/elasticInterface/clienttest:/opt/client
    rest-interface:
        #build: backend/RESTinterface
        image: docker.io/library/restinterface:0.0.1-SNAPSHOT
        depends_on:
            - redis
            - kafka
        networks: 
            - entomomachia
        environment:
            - DOCKER_RUNNING=true
        volumes:
            - ./logs:/opt/logs/
            - ./backend/RESTinterface:/opt/RESTinterface
        ports:
            - 8888:8888
    
    redis:
        image: redis
        stdin_open: true 
        tty: true
        ports: 
            - 6379:6379
        networks: 
            - entomomachia
    


networks:
    entomomachia:
        external: false

volumes:
    permanentdata: 
